[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
    "@chainlink=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "foundry-devops/=lib/foundry-devops/src/",
    "@openzeppelin=lib/openzeppelin-contracts/contracts/",


]
auto_detect_remappings = true


fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./public/" },
]


[invariant]
runs = 128
depth = 128


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
